services:
  portfolio:
    image: ghcr.io/milindmadhukar/portfolio:latest
    container_name: portfolio
    restart: always
    environment:
      - NODE_ENV=production
      - BLOG_REPO_URL=${BLOG_REPO_URL}
      - LANYARD_SOCKET_URL=${LANYARD_SOCKET_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}

  ssh-portfolio:
    image: ghcr.io/milindmadhukar/portfolio-ssh:latest
    container_name: ssh-portfolio
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./ssh_data:/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
